#!/bin/sh

### BEGIN INIT INFO
# Provides:          grafana
# Required-Start:    $local_fs $remote_fs $syslog $time
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: grafana
# Description:       Manage the grafana server
### END INIT INFO

GRAFANA_DIR=/opt/grafana
GRAFANA_BIN=${GRAFANA_DIR}/bin/grafana-server
GRAFANA_CFG=/etc/grafana/grafana.ini
GRAFANA_USER=grafana
PIDFILE=/var/log/grafana/grafana.pid
LOGFILE=/var/log/grafana/grafana.log

# Read configuration variable file if it is present
[ -r /etc/default/grafana ] && . /etc/default/grafana

case "$1" in
    "start")
	echo "Starting grafana..."
	su ${GRAFANA_USER} -c "${GRAFANA_BIN} -homepath ${GRAFANA_DIR} -config ${GRAFANA_CFG} -pidfile ${PIDFILE} >> ${LOGFILE} 2>&1 &"
	echo "done"
	;;

    "stop")
	echo "Stopping grafana..."
	if [ -f ${PIDFILE} ]; then
	    kill `cat ${PIDFILE}`
	    rm ${PIDFILE}
	    echo "done"
	else
	    echo "not running?"
	fi
	;;

    "restart")
	echo "Restarting grafana..."
	$0 stop
	sleep 2
	$0 start
	;;

    *)
	echo "$0 [start|stop|restart]"
	;;

esac
